[package]
name = "s3_compatible"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
aws-sdk-s3 = "1.93.0"
aws-types = "1.3.7"
aws-credential-types = "1.2.3"
