[package]
name = "http_request"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version =  "1.43.0", features = ["full"] }
